"""users table

Revision ID: 4da0de899bfc
Revises: 
Create Date: 2022-05-17 04:51:22.206087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da0de899bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('userFirstName', sa.String(length=20), nullable=False),
    sa.Column('userLastName', sa.String(length=20), nullable=True),
    sa.Column('userEmail', sa.String(length=120), nullable=False),
    sa.Column('user_phone_number', sa.String(length=10), nullable=True),
    sa.Column('userProfilePic', sa.String(length=20), nullable=False),
    sa.Column('userPassword', sa.String(length=128), nullable=True),
    sa.Column('userStatus', sa.Boolean(), nullable=True),
    sa.Column('userGender', sa.Enum('male', 'femal', 'other', name='varcher'), nullable=True),
    sa.Column('userDateOfBirth', sa.Date(), nullable=True),
    sa.Column('userLoginAt', sa.DateTime(), nullable=True),
    sa.Column('userCreationDate', sa.DateTime(), nullable=False),
    sa.Column('userRoles', sa.Enum('superAdmin', 'admin', 'student'), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('user_phone_number')
    )
    op.create_index(op.f('ix_user_userEmail'), 'user', ['userEmail'], unique=True)
    op.create_index(op.f('ix_user_userName'), 'user', ['userName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userName'), table_name='user')
    op.drop_index(op.f('ix_user_userEmail'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
